name: action-mongo-atlas-nuke
description: https://github.com/champ-oss/action-mongo-atlas-nuke
inputs:
  MONGODB_ATLAS_PRIVATE_KEY:
    description: 'mongo atlas private key'
    required: true
  MONGODB_ATLAS_PUBLIC_KEY:
    description: 'mongo atlas public key'
    required: true
  MONGODB_PROJECT_ID_LIST:
    description: 'mongo project id list'
    required: true
runs:
  using: "composite"
  steps:
    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install mongo atlas requirements
      shell: bash
      run: cd ${{github.action_path}} && pip3 install -r requirements.txt
    - name: run mongo nuke action
      shell: bash
      env:
        MONGODB_ATLAS_PRIVATE_KEY: ${{ inputs.MONGODB_ATLAS_PRIVATE_KEY }}
        MONGODB_ATLAS_PUBLIC_KEY: ${{ inputs.MONGODB_ATLAS_PUBLIC_KEY }}
        MONGODB_PROJECT_ID_LIST: ${{ inputs.MONGODB_PROJECT_ID_LIST }}
      run: |
        python ${GITHUB_ACTION_PATH}/action-mongo-atlas-nuke.py